import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Nabvar from "@/components/Nabvar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Social Book",
  description: "Generated by nextjs",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Nabvar />
          <div className="bg-gray-100 px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-56">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
