import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Nabvar from "@/components/Nabvar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Social Book",
  description: "Generated by nextjs",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Nabvar />
        {/* <div className="w-full  px-4 md:px-8 lg:px-16 xl:32 2xl:px-64"> */}
        {/* <div className="w-screen mx-auto max-w-screen-xl px-4 lg:px-8 bg-gray-200"> */}
        <div className=" bg-gray-200 px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-56">
          {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
